server:
  port: 8081
  servlet:
    session:
      timeout: 120m

spring:
  session:
    timeout: 120m
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev

pear:
  security:
    super-auth-open: true
    super-admin: admin
    maximum: 1
    remember-key: PEAR_REMEMBER
    open-api:
      - /login/**  # 开放登录接口
      - /system/captcha/** # 开放验证码接口
      - /assets/** # 开放静态资源
      - /admin/** # 开放静态资源
      - /component/** # 开放静态资源
      - /favicon.ico # 开放FAVICON
  upload:
    windows-path: D:\home\uploads\
    linux-path: /home/uploads/
    ftp-use: false
    hostname:
    port: 0000
    username:
    password:

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  mapper-locations: classpath*:**/xml/**.xml
  type-aliases-package: com.pearadmin
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl